### ISSUE TITLE
CI integration

### ISSUE THREAD

**Issue by ricardojmendez** [ptaoussanis/faraday#104]
Integrate with Travis CI. I actually have a build setup already on my personal clone, which I use for tests, but the build is sometimes failing with 

```
Oct 07, 2016 6:14:23 AM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: Connection refused
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
```

Doesn't do it consistently, though. Not sure what's up. Filing an issue to keep track of it.

**Comment by ricardojmendez** [comment]
Stil reviewing.

Thought that the root cause might be that it's trapping the exit of the first test round and killing DynamoDBLocal, since the first round goes as planned.  That doesn't happen on OS X, but seems to happen on whatever distribution the container is running (Debian?).

Adding a --no-kill flag where I don't attempt to kill DynamoDBLocal on exit did not solve it.

**Comment by ricardojmendez** [comment]
The goal here is to have CI integration, not necessarily Travis specifically. Tests work as expected on Gitlab CI for me, so it's likely an issue of the distribution used for this image killing DynamoDBLocal before it's ready.

Don't have any more bandwidth to pursue this right now, so closing. Leaving Gitlab integration in, which I'll continue to use for my personal WIP clone.

**Comment by ricardojmendez** [comment]
Following up on this.

I thought that the issue with DynamoDBLocal being killed might be due to the old legacy infrastructure.  I've tested it on the containerized version, [as described here](https://docs.travis-ci.com/user/migrating-from-legacy/), but it's still killed at some point during the tests.

The [Gitlab CI version](https://gitlab.com/ricardojmendez/faraday/pipelines) continues to work consistently. I might just set up that repository to clone this one.

**Comment by ptaoussanis** [comment]
FWIW, think very low traffic repos like this one might not necessarily be worth the added effort / headaches for CI. For my part, happy to just manually run tests before committing mainline changes - but happy to leave the choice to you since I think it'll mostly affect you.

**Comment by ricardojmendez** [comment]
I think it has value anyway. I already have it working smoothly with Gitlab, but Travis refuses to cooperate. :-P I'll probably give up on Travis for now and leave as-is.  

I've set up my Gitlab repository to clone this one hourly, will add the build badge to the README.
