### ISSUE TITLE
Is the scan function safe for large tables?

### ISSUE THREAD

**Issue by brosenan** [ptaoussanis/faraday#112]
Is the `scan` function safe to use with extremely large tables?  I see from the code that it handles pagination by concatenating paginated results into a single sequence using `merge-more`, but I couldn't figure out from reading the code whether this sequence is lazy.

If this sequence is not lazy there are of-course two major drawbacks when using it with large tables:
1. Scan will return after consuming the entire table, or the entire segment (if assigned) and
2. Scan will consume all available memory and crash when no more memory is left.

I believe the sequence is lazy, just wanted to make sure.

Thanks,
Boaz

**Comment by geekingfrog** [comment]
`scan` will not actually scan the whole table. It will return a (strict) array of elements, with some metadata. One the meta-data key is `last-prim-kvs`. If this is not null, it means the scan isn't complete and you'll have to call `scan` again supplying this `last-prim-kvs` to continue scanning.

**Comment by rwilson** [comment]
Here's a similar approach to @geekingfrog, but operating semi-lazily:
```clojure
(defn lazy-scan
  ([client-opts table] (lazy-scan client-opts table nil))
  ([client-opts table opts]
   (lazy-seq
    (let [results (faraday/scan client-opts table opts)
          next-kvs (:last-prim-kvs (meta results))]
      (if next-kvs
        (lazy-cat results (lazy-scan client-opts table (assoc opts :last-prim-kvs next-kvs)))
        results)))))
```

I say semi-lazily, because production will stay ahead of consumption, but in chunks related somewhat to whatever initial `:limit` value is specified in `opts`.

**Comment by rwilson** [comment]
I think it can be closed; it's reasonably well documented already via the AWS docs and the `:limit` parameter.

**Comment by belucid** [comment]
Sounds good @rwilson

**Comment by green-coder** [comment]
I think that the original poster's question have been misunderstood. He went to read the source code, found the function `merge-more`, expressed concerns about what it does, but nobody answered about that function w.r.t. lazyness.

**Comment by green-coder** [comment]
@brosenan To get just a piece of the query's result, you need to specify `{:limit n, :span-reqs {:max m}}` in the options. You will get up to `(* n m)` items in your results, i.e. `m` requests of up to `n` items concatenated together.

By default, `(-> options :span-reqs :max)` is set to 5 in the current version of Faraday (`1.9.0`).
