### ISSUE TITLE
Upgrade to 1.11.16+ of aws-sdk-java for task-level IAM role support in AWS ECS

### ISSUE THREAD

**Issue by codeasone** [ptaoussanis/faraday#113]
My application is running in an AWS ECS container that has [task-level](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html) IAM policy associated with it. 

Support for assuming task roles via the default credentials provider chain was added to `aws-sdk-java` in version [1.11.16](https://github.com/aws/aws-sdk-java/blame/7844c64cf248aed889811bf2e871ad6b276a89ca/aws-java-sdk-core/src/main/java/com/amazonaws/auth/EC2ContainerCredentialsProviderWrapper.java#L28)

Please consider upgrading to a `1.11.16` or later release of the SDKs as part of the next release. 

I have a fork which I'm using to work-around this issue. I've used `1.11.126` and am not seeing any significant issues. 

However, I did see [one error](https://gist.github.com/codeasone/e11c15e7ed532302424357295a08877c) running the tests.

**Comment by ricardojmendez** [comment]
> I have a fork which I'm using to work-around this issue. I've used 1.11.126 and am not seeing any significant issues.

Can you make a pull request?

**Comment by codeasone** [comment]
@ricardojmendez I just bumped the version in the `project.clj`, which doesn't justify a PR.

**Comment by codeasone** [comment]
A simple work-around for this limitation is simply putting the amazon SDK dependency ahead of `faraday` in your `project.clj`: 

```
[com.amazonaws/aws-java-sdk-dynamodb "1.11.126"]
[com.taoensso/faraday "1.9.0"]
```

**Comment by zarkone** [comment]
@codeasone sorry, but why it doesn't justify a PR? I would be glad to remove this line from deps

**Comment by codeasone** [comment]
Why would you remove the dependency `aws-java-sdk-dynamodb`, which is required - perhaps I'm not understanding what you mean by:

> [...] remove this line from the deps 

Here is a PR to bump the version my current projects uses, and which addresses the original issue without having to mitigate via Clojure's dependency resolution process. https://github.com/ptaoussanis/faraday/pull/117

**Comment by zarkone** [comment]
@codeasone Sorry that my words was not clear...

Before, you suggested to add `1.11.126` to `project.clj` before faraday to workaround this issue. This is what I did, and it works for me. But I would be glad to remove this dependency from my `project.clj`, not faraday's, i.e. have this dependency updated inside faraday. So, thanks for your PR!

**Comment by Lokeh** [comment]
How did you guys configure faraday to use dynamodb without providing credentials?

**Comment by belucid** [comment]
Part of 1.10. Beta forthcoming.

**Comment by jvtrigueros** [comment]
@Lokeh not to add too much noise to this issue, but you have to provide credentials, if you're looking to use DynamoDB Local (which requires no credentials) add these in your `client-opts`:
```clojure
{:access-key ""
 :secret-key ""}
```
