### ISSUE TITLE
Release 1.6.0

### ISSUE THREAD

**Issue by mantree** [ptaoussanis/faraday#46]
In order to get 1.6.0 out the door some testing needs to be done.

I'm putting these together over at mixradio-forks/faraday, so if there are any comments or test suggestions create issues over there.

I've taken the step to include the local dynamo runner in the repo. This will allow contributors in the future to just clone, test and get on their way. Let me know if that breaks an assumption somewhere.

**Comment by ptaoussanis** [comment]
Just pushed `[com.taoensso/faraday "1.6.0-beta1"]` to Clojars. Thanks again for your assistance (and patience). Cheers! :-)

**Comment by ptaoussanis** [comment]
Just pushed [com.taoensso/faraday "1.6.0"] to Clojars, cheers :-)
