### ISSUE TITLE
Faraday fails to connect when my ec2 instance is run under a role

### ISSUE THREAD

**Issue by shinep** [ptaoussanis/faraday#53]
My ec2 instance is running with a federated role from IAM and I am trying to use faraday without providing any key/secret credentials. Its a bug in the reflection code and I have a tested one line fix for it.

The problem is in the latest beta release.

**Comment by ptaoussanis** [comment]
Hi Shine, would be happy to see a PR - thanks! :-)

**Comment by shinep** [comment]
PR done.

**Comment by ptaoussanis** [comment]
Closing since fix has already been merged (thanks again).
