### ISSUE TITLE
Support for regions

### ISSUE THREAD

**Issue by madeye-matt** [ptaoussanis/faraday#57]
Working in Europe means we need to keep all our data in the Amazon EU zones. A quick grep of the code shows faraday to be region agnostic and thus assumes all data is held in (presumably) one of the US zones.

In the AWS API region can be set on the AmazonDBClient as follows (using clojure syntax):
(.setRegion (com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.) (com.amazonaws.regions.Region/getRegion com.amazonaws.regions.Regions/EU_WEST_1))

Might have a look at this myself if I get time - for now leaving it as a feature request :-)

**Comment by tlipski** [comment]
Please see the discussion in #56.

Still, I think that the Connecting section of README.md could use an explaination how to connect to different regions.

**Comment by madeye-matt** [comment]
Thanks for the prompt reply - will update the README if I get the chance.  For the record, the enpoint can be set as follows:
{:endpoint "http://dynamodb.eu-west-1.amazonaws.com", :secret-key "XXX", :access-key "XXX"}
where :endpoint is selected from the list shown [here](http://docs.aws.amazon.com/general/latest/gr/rande.html#ddb_region)

**Comment by ptaoussanis** [comment]
Hi @madeye-matt, will take a look at your PR in a moment (thanks!).

@tlipski Thanks again for helping keep on top of support questions Tomek, much appreciated :-)
