### ISSUE TITLE
Slim down AWS dependencies

### ISSUE THREAD

**Issue by jaley** [ptaoussanis/faraday#60]
Hello!

```clj
[com.amazonaws/aws-java-sdk "1.9.25" :exclusions [joda-time]]
```

Does Faraday need the full AWS SDK? It makes for a rather large uberjar. Presumably only the DDB, and maybe core jars are required? Amazon provide [separate jars](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.amazonaws%22) for the different services.

**Comment by ptaoussanis** [comment]
Hi James,

Thanks for pinging me about this. Wasn't actually aware that separate jars are available - would be happy to accept a PR that swapped to the appropriate dep. All we should need is the DDB client.

Cheers! :-)
