### ISSUE TITLE
put-item :return crashing

### ISSUE THREAD

**Issue by skbach** [ptaoussanis/faraday#64]
(far/put-item client-opts "foo" {:uri "yyy" :_id "42"} {:return :all-new})
>> AmazonServiceException Return values set to invalid value

Am I missing something simple or is this a bug?
Thanks.

**Comment by ptaoussanis** [comment]
Hi there, it seems the valid values here are only :none or :return-old, Ref. http://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/P_Amazon_DynamoDBv2_Model_PutItemRequest_ReturnValues.htm

**Comment by skbach** [comment]
Only :none and :all-old are valid for put-item it appears.

Very confusing though because the aws spec then says at the bottom:

Allowed Values
NONE, ALL_OLD, UPDATED_OLD, ALL_NEW, UPDATED_NEW

But only some of those apply to put I guess, and the others work (maybe?) with an update-item.
