### ISSUE TITLE
Connect without explicit key/secret client-opts?

### ISSUE THREAD

**Issue by skbach** [ptaoussanis/faraday#66]
Is it possible to overload get/query etc so that they use the IAM environment rather than explicit user/password combinations.

I know the SQS api for example has overloads that don't require credentials and therefore defaults to IAM roles, so I'm wondering if the underlying Dynamo api and/or faraday are capable of doing this.

Currently I have to put the password directly into the shell scripts environment in order to connect.

Thanks.

**Comment by ptaoussanis** [comment]
Hi Scott, you'll want to check  the `db-client*` source (here)[https://github.com/ptaoussanis/faraday/blob/master/src/taoensso/faraday.clj#L88] to see in detail exactly what connection types Faraday supports.

Does that help?

**Comment by skbach** [comment]
Thanks Peter!
