### ISSUE TITLE
How do you use the default credential chain?

### ISSUE THREAD

**Issue by hmgibson23** [ptaoussanis/faraday#69]
Seems a little annoying to have to specify credentials on an EC2 instance.

**Comment by paulheideman** [comment]
It might work if you just leave the credentials out of the map. It does on Elastic Beanstalk.

**Comment by mantree** [comment]
@paulheideman got it right. Just leave them out and the client will find the creds via the ec2 role you have assigned.

**Comment by rwillig** [comment]
@paulheideman does this mean a map like {:access-key "" :secret-key ""} or an empty map {} ?

**Comment by paulheideman** [comment]
I have a map with just the endpoint specified, but an empty map should work too.

```{:endpoint   (System/getProperty "DYNAMODB_ENDPOINT" "http://localhost:8000")}```
