### ISSUE TITLE
:return :count doesn't work

### ISSUE THREAD

**Issue by arohner** [ptaoussanis/faraday#71]
```clojure
(far/query ddb t {:foo foo}
                          {:index "my-index"
                           :return :count})
```

Returns `[]` rather than a count. It appears `merge-more` is to blame.

**Comment by ptaoussanis** [comment]
Thanks for the report Allen, PR to fix welcome!

**Comment by ptaoussanis** [comment]
Closing to focus discussion at https://github.com/ptaoussanis/faraday/issues/91
