### ISSUE TITLE
Queries with compound conditions

### ISSUE THREAD

**Issue by rahulmutt** [ptaoussanis/faraday#75]
For example, suppose there is a table A with attribute B. I would like to collect all items such that (A.B = 0 OR A.B = 2). From what I see in the library, this doesn't seem to be implemented yet and would require one to execute a more general query and filter the results manually. How difficult would it be to implement compound conditional operators :or and :and and the rest of the condition expression syntax mentioned [here](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.SpecifyingConditions.html)?

If you could give me a quick idea of which parts of the API have to be changed, I can submit a PR a bit faster. Thanks.

**Comment by ptaoussanis** [comment]
Hi Rahul,

@leonardoborges recently added support for expression support at https://github.com/ptaoussanis/faraday/pull/73 - could that be what you're looking for?

The changes are currently on the [dev branch](https://github.com/ptaoussanis/faraday/tree/dev) and Clojars as `[com.taoensso/faraday "1.9.0-alpha2"]`

**Comment by rahulmutt** [comment]
Thanks! That sets up the basic infrastructure for what I want. I just need to adapt whatever was done to update-item and put-item to query.

**Comment by ptaoussanis** [comment]
Sounds good, PR welcome!

**Comment by rahulmutt** [comment]
As I read through the query code and consulted the AWS docs, I realized that I can accomplish my specific query with the IN operator. But the fact still remains that faraday is currently using the legacy way of filtering queries.

I suggest that we consider the current query-filter parameter as a mini-DSL that is compiled into a condition expression (the new API for DynamoDB). I'll leave this issue open as a feature request for updating faraday to implement this DSL to maintain the simple interface while keeping it up to date with the updated DynamoDB API.

**Comment by ricardojmendez** [comment]
It would seem like the original request is something that can be handled with filter expressions, which I added on #76. 

@rahulmutt  Could you take a look [at these tests](https://github.com/ptaoussanis/faraday/commit/cb2f1b1570a7b6db186cd5b17b6626cc8f05bbc7#diff-eb45e1f169385fa1d90ecb43a6665568R447) and see if it provides what you were aiming for?

**Comment by ptaoussanis** [comment]
I believe this has been addressed by @ricardojmendez's recent work so closing.

@rahulmutt: please feel free to reopen if you're still having trouble.
