### ISSUE TITLE
Does update-table only support provisioned throughput?

### ISSUE THREAD

**Issue by ricardojmendez** [ptaoussanis/faraday#77]
I'd like to confirm - does update-table only support provisioned throughput? I can provide a pull request to  add other functionality as well, such as updating secondary indexes, but wanted to confirm first that it's not already supported elsewhere (I'm new to faraday).

**Comment by ptaoussanis** [comment]
Hi Ricardo, that's correct - current `update-table` supports only throughput changes. 

Would be happy to see a PR with other functionality, thank you! Please target the `dev` branch for any PR work.

Cheers :-)

**Comment by ricardojmendez** [comment]
Thanks. Closing the issue, as it was specific to the question. I may add some more features but will get acquainted with the dev brach first,to get familiar with the parameter conventions.
