### ISSUE TITLE
Implementation discussion: update-table changes

### ISSUE THREAD

**Issue by ricardojmendez** [ptaoussanis/faraday#78]
I'm looking into expanding update-table to add other functionality, like GlobalSecondaryIndexUpdates, since as discussed on #77, it only currently supports provisioned throughput for the table.

I see the following issues:

- Currently it expects a throughput map as a parameter, when you don't necessarily want to change the throughput for the table.
- The map is _specifically_ for throughput, when we should be receiving a map of values to change, for example, a description of :gsindexes updates to do.

I'm inclined to change that third parameter to `update-table` to just be a map with the settings for the operations to apply. This would be consistent with how the table description is passed to `create-table` and would solve both problems above, but since that'd be a breaking change I'd rather bring it up first.

Thoughts?

**Comment by ptaoussanis** [comment]
Hi Ricardo,

The breaking change you have in mind sounds good to me, thanks for checking.

**Comment by ricardojmendez** [comment]
It looks like `update-table`'s implementation right now is very throughput-specific, including mapping the update call on a series of throughput increase steps and returning the last one executed.

Is there a reason for this?  I'm going through the referenced page but don't see a reason why the update request would be executed in steps, only the explanation for the decrease limit in a 24 hour period.

**Comment by ptaoussanis** [comment]
Was the case previously that large throughput increases needed manual steps. Not sure if that's still the case or not. If not, that code's vestigial and can be removed.

**Comment by ricardojmendez** [comment]
Perfect. I'll see about removing it and running some tests against an actual live instance, since I've read some remarks that the local instance disregards throughput settings (it referred to global secondary indexes, but I expect is a general characteristic).

**Comment by ricardojmendez** [comment]
No problem, I'll test. If the limits no longer exist then things would be much simpler, since I can just unify all the table updates - otherwise it'd be best to keep separate `update-table` and `update-table-throughput` functions.

**Comment by ricardojmendez** [comment]
Testing against a live cloud instance, I can get the update to throughput to apply in a single step. Will prune that old code.

**Comment by ptaoussanis** [comment]
Just confirming: that's for a large increase, yes? I.e. more than 2x or 4x the previous value?

**Comment by ricardojmendez** [comment]
Correct, tried it going from {:read 1 :write 1} to {:read 16 :write 16} without stepping. No error and update returned the expected values

```clojure
{:lsindexes nil,
 :gsindexes nil,
 :name :temp_table_1450109428934,
 :throughput
 {:read 16,
  :write 16,
  :last-decrease #inst "1970-01-01T00:00:00.000-00:00",
  :last-increase #inst "1970-01-01T00:00:00.000-00:00",
  :num-decreases-today 0},
 :prim-keys {:artist {:key-type :hash, :data-type :s}},
 :size 0,
 :status :active,
 :item-count 0,
 :creation-date #inst "2015-12-14T16:10:28.944-00:00",
 :indexes nil}
```

**Comment by ptaoussanis** [comment]
Great, happy to see that they've removed that limit- thanks for picking up on this.

**Comment by ricardojmendez** [comment]
Closing along with #80
