### ISSUE TITLE
Handling update-table exceptions

### ISSUE THREAD

**Issue by ricardojmendez** [ptaoussanis/faraday#85]
If I'm reading this correctly... if we have an exception on `update-table`, then the promise will never be delivered, and any calls deref'ing it will hang. Is that correct?  Is there a better way to handle this, for instance, delivering `nil`?

I'm new to futures and promises, and there doesn't seem to be a way to cancel an un-delivered promise like there is to cancel a future.

**Comment by ptaoussanis** [comment]
Will be addressing this shortly, closing.
