### ISSUE TITLE
Release 1.9 alpha 3

### ISSUE THREAD

**Issue by ricardojmendez** [ptaoussanis/faraday#87]
Hey Peter,

I think I'm done with the major changes for now - this would be a good point at which to send out an alpha 3 to Clojars.

Cheers!

**Comment by ptaoussanis** [comment]
Will look shortly, thanks!

**Comment by ptaoussanis** [comment]
Just a heads-up: please pause further development until I've integrated all current changes. Will try get these in asap.

**Comment by ricardojmendez** [comment]
Acknowledged. If I have to do any other changes, I'll do them on feature branches and leave them unmerged for now.

**Comment by ptaoussanis** [comment]
Okay, have updated `[com.taoensso/faraday "1.9.0-SNAPSHOT"]` - changelog is [here](https://github.com/ptaoussanis/faraday/blob/dev/CHANGELOG.md).

Could I possibly ask you to rebase against the current `dev` branch and update your tests for https://github.com/ptaoussanis/faraday/commit/e8fa44ae3f55ba735b8f9f2afb3facbca93df8de and https://github.com/ptaoussanis/faraday/commit/07f1489e20b75941f37a6543235906cbabd2837c?

Renamed these options to keep the types clearer / to avoid confusion. Don't mind if something's a little unclear at first (e.g. `proj` for `projection`) so long as it's consistent and unambiguous once you understand the meaning. In this way I feel `proj-expr` is less ambiguous than, say, `projection` - since there's a number of uses of "projection" in Faraday and in keeping the `expr` we keep it clear what type we have in mind here. Does that seem reasonable?

If you can confirm that everything else still seems to be working okay, then I'll cut an `alpha3` release.

Appreciate all the time you've put in on this, it's been a huge help.

**Comment by ricardojmendez** [comment]
Wondering about the rebase you did: Not a fan of finishing feature branches with a recursive merge on dev?  

> There's no other breaking changes on your end, yes?

None planned right now.

> Could I possibly ask you to rebase against the current dev branch and update your tests for e8fa44a and 07f1489?

Sure, will do early tomorrow.

> Appreciate all the time you've put in on this, it's been a huge help.

Glad it could contribute!

**Comment by ptaoussanis** [comment]
> Wondering about the rebase you did

Not a general rule, just keeping things organized since you had a lot of commits coming in.

> None planned right now.

Sorry, I mean other breaking changes already in that I may have missed while compiling the changelog.


Cheers :-)

**Comment by ricardojmendez** [comment]
I've re-done the tests for those commits, but tests are now failing (in a variety of ways) after the change from commit 484ee3d for issue #63.  

It's not only my tests either, the `batch-write-item` call on the first tests after _;;;; Basic API_ throws an exception as well.


```clojure
(after-setup!
   #(far/batch-write-item *client-opts*
                          {ttable {:delete [{:id 0} {:id 1} {:id 2}]}}))
```

Fails with:

```
Exception in thread "Thread-0" java.lang.ClassCastException: java.lang.Integer cannot be cast to clojure.lang.Named
	at clojure.core$name.invokeStatic(core.clj:1545)
	at clojure.core$name.invoke(core.clj:1539)
	at taoensso.faraday.utils$map_kvs$fn__7763.invoke(utils.clj:7)
	at  [...]
```

How do you want to handle this? It's not clear what `*attr-multi-vs?` is supposed to indicate, since there are no comments. All tests pass if it defaults to true. It doesn't seem to be an issue of simply passing it on the opts for `batch-write-item`, as the test above still barfs on that test.

Should I just push the commits as the tests work when it defaults to true, and let you deal with the breaking chance?

**Comment by ricardojmendez** [comment]
Regarding breaking changes: yes, one's missing.  See commit 4e1bbbe - update-table used to always expect the throughput, which is now optional, and that parameter is instead a map of possible changes.

**Comment by ptaoussanis** [comment]
Thanks, will take a look at getting everything finished up today!

**Comment by ptaoussanis** [comment]
Updated `[com.taoensso/faraday "1.9.0-SNAPSHOT"]` - changelog is [here](https://github.com/ptaoussanis/faraday/blob/dev/CHANGELOG.md).

Local tests passing on my end, but I'm not using DDB so please confirm? If you give me the go-ahead, will cut an alpha3.

**Comment by ricardojmendez** [comment]
Hmm, tests seem to get stuck against a local DynamoDB instance after 

> Reflection warning, expectations.clj:566:16 - reference to field ns can't be resolved.
> Reflection warning, expectations.clj:566:28 - reference to field sym can't be resolved.

This is what happened when we got an exception and a promise didn't get delivered.

Eventually they do fail with an error where it seems like it's attempting to modify an index while an operation is in process, but I do see the index-status-watch calls on the test. Will do further review.

**Comment by ptaoussanis** [comment]
Anything special I need to do to reproduce that?

I'm just running `./run-tests local` on my end and everything's passing. FYI current HEAD is 711a1fc.

**Comment by ptaoussanis** [comment]
Would also note that the current HEAD no longer uses promises anywhere for this reason. The promises where unnecessary so just switched them out for plain futures which'll rethrow errors on deref.

**Comment by ricardojmendez** [comment]
Nope, just booted a local instance I'm using for other tests and ran `lein test`. Using `./run-tests local` the tests do seem to pass.

Nevermind. Restarted that instance and tests pass as expected.

**Comment by ricardojmendez** [comment]
Updated and tested against my own code, all good on that end as well. Thumbs up for release from me!

**Comment by ricardojmendez** [comment]
BTW, just noticed a typo on the changelog:

> ## v1.7.1 / 2015 June 4

> This is a non-breaking maintenance elease

Notice **elease**

**Comment by ptaoussanis** [comment]
Great, thanks - just pushed `[com.taoensso/faraday "1.9.0-alpha3"]` to Clojars
