### ISSUE TITLE
Looking for feedback on upcoming Faraday v1.9 release

### ISSUE THREAD

**Issue by ptaoussanis** [ptaoussanis/faraday#88]
`[com.taoensso/faraday "1.9.0-alpha3"]` is now up on Clojars with a significant set of [changes](https://github.com/ptaoussanis/faraday/blob/dev/CHANGELOG.md). Big thanks to @ricardojmendez for the bulk of this work.

I don't use DynamoDB myself so would ask for a quick show of hands if the proposed changes for v1.9 look good to everyone. If anything's of concern, now would be the best time to report.

If anyone has some time + feels like helping out, would appreciate confirmations of alpha3 running okay on internal/application tests, etc. **Please report any unexpected problems / breakages**.

Pinging: @paraseba, @tlipski, @joelittlejohn, @moea, @mantree, @leonardoborges

Thanks a lot, hope everyone's having a good holiday season! Cheers :-)

**Comment by joelittlejohn** [comment]
Hey @ptaoussanis. Thanks for mentioning this, looks like there are some great changes in this release.

I integrated 1.9.0-alpha3 into a selection of our services and ran their test suites. After the required changes for `update-item` all tests ran successfully. We can consider this at least a basic sanity check for:

```
as-map
batch-get-item
batch-write-item
clj-item->db-item
delete-item
delete-item-request
delete-table
describe-table
ensure-table
freeze
get-item
list-tables
put-item
put-item-request
query
query-request
update-item
``` 

I can't really comment on how exhaustive these tests are (it varies :smile:), but hopefully that will give you a little confidence.

**Comment by ptaoussanis** [comment]
@joelittlejohn Exactly what I was looking for, thanks Joe!

**Comment by ptaoussanis** [comment]
@ricardojmendez Hi Ricardo, wanted to get your input on the current v1.9 dev branch- is it essentially API stable?

Am ready to publish a public beta whenever you give me the go-ahead.

Thanks! :-)

**Comment by ricardojmendez** [comment]
Hi Peter,

I have no breaking changes planned.  I expect the API will remain as is, and we can later figure out how to best support the new APIs separately (probably under a different namespace).

I'd say go ahead!

**Comment by ptaoussanis** [comment]
Done! Thanks-
