### ISSUE TITLE
Expand expression tests, remove update-map tests

### ISSUE THREAD

**Issue by ricardojmendez** [ptaoussanis/faraday#89]
We need more expression tests, as most of the current tests now use `update-map`.  It might also be a good time to convert existing `update-map` tests to use `update-expr`.

**Comment by ptaoussanis** [comment]
Sounds good, PR welcome- thanks!

An aside: if possible, would prefer that we stick to the current set of issue labels since I use a standardized set across all my repos via the GitHub API.

Cheers :-)

**Comment by ricardojmendez** [comment]
Acknowledged. I normally think of "enhancement" as something functionality related, but it fits.

**Comment by ptaoussanis** [comment]
To keep from needing to many labels, I use `enhancement` as a catchall for all non-bug-fix improvements - incl. new features, documentation improvements, new/better tests, etc.
