### ISSUE TITLE
How to add AND OR clause to prim-key-conds/query-filter in Query/Scan API call

### ISSUE THREAD

**Issue by mj-jadhav** [ptaoussanis/faraday#93]
Currently I don't see a way to add AND/OR clause to query/scan API call. Can you please suggest workaround for it? or If it exists in this library then can you please share an example?
I want to do something like this:
```
Get me all the items where attribute1 = 0 or attribute1>10
```

**Comment by ricardojmendez** [comment]
Looks like you're looking for filter expressions, which made it into 1.9-alpha-3.

https://github.com/ptaoussanis/faraday/blob/dev/test/taoensso/faraday/tests/main.clj#L500-L504

http://numergent.com/2016-01/Clojure-and-DynamoDB-with-Faraday-part-2.html
