### ISSUE TITLE
Scan using nested attributes

### ISSUE THREAD

**Issue by yawningman** [ptaoussanis/faraday#94]
Hi there, firstly thanks for providing this useful clojure library for DynamoDB - I have a question:

Given the following item:

``` Clojure
(dyndb/put-item client-opts
                :my-table
                {:id 17 :event-type :points-earned :data {:tx-id "123455"}})
```

The following `scan` works as expected and finds the correct item(i.e find all items with `event-type == :points-earned`):

``` clojure
(dyndb/scan client-opts
            :my-table
            {:attr-conds {:event-type [:eq :points-earned]}})
```

However, I would like to perform a scan where `data.tx-id == "123455" ` but this query always returns an empty result set - is this possible and how do I specify scanning on a nested attribute(dot notation appears to not work):

``` clojure
;; Always returns [] despite items with data.tx-id == "123455"
(dyndb/scan client-opts
            :my-table
            {:attr-conds {"data.tx-id" [:eq "123455"]}})
```

Thanks in advance, appreciated any info.

**Comment by ricardojmendez** [comment]
Fir nested attributes, you'll need a filter expression.  [Check out Part 2 of this tutorial](http://numergent.com/2016-01/Clojure-and-DynamoDB-with-Faraday-part-2.html).  Given your attribute has a dash in the name, you'll need to use expression attribute names as well - you can read more about the reason on the section on projection expressions on the same page.

**Comment by yawningman** [comment]
Thanks for the response - I've tried using a filter expression based on [the tutorial](http://numergent.com/2016-01/Clojure-and-DynamoDB-with-Faraday-part-2.html) with the `scan` function(the tutorial is using the `query` function which assumes indexes).

This time is seems to return ALL items despite the filter being provided - am I missing something obvious?

``` clojure
;; Returns all ITEMS(as opposed to only items with data.tx-id = "123455"
(dyndb/scan client-opts
            :my-table
            {:filter-expr "#data.#tx-id = :tx-id"
             :expr-attr-names {"#data" "data"
                               "#tx-id" "tx-id"}
             :expr-attr-vals {":tx-id" "123455"}})
```

**Comment by ricardojmendez** [comment]
At first glance that looks OK - which version of the library are you using? Those features made it into 1.9, but weren't there for 1.8.

[You can see the tests here](https://github.com/ptaoussanis/faraday/commit/6311c4ede72ccb71f3fa47828d798c510af90715).

**Comment by yawningman** [comment]
Thanks - I was using `1.8.0`, after switching to `1.9.0-beta1` the filters starting working! yay

``` clojure
(let [tx-id "123455"]
  (dyndb/scan client-opts
              :my-table
              {:filter-expr "#data.#tx_id = :tx_id"
               :expr-attr-names {"#data" "data" 
                                 "#tx_id" "tx-id"}
               :expr-attr-vals {":tx_id" tx-id}}))
```
(Side note: I ended up having to include a `data` key in `:expr-attr-names` as when I used `data.#tx_id` it complained that `data` is a reserved keyword)

Thanks and much appreciated

**Comment by ricardojmendez** [comment]
> (Side note: I ended up having to include a data key in :expr-attr-names as when I used data.#tx_id it complained that data is a reserved keyword)

Ah, yeah, of course it would be.

Glad you got it working!
