### ISSUE TITLE
Jackson error with 1.9.0-alpha3

### ISSUE THREAD

**Issue by dfcarpenter** [ptaoussanis/faraday#97]
I can use 1.8.0 just fine but when I try to use the latest alpha I keep getting 

```   
NoSuchMethodError com.fasterxml.jackson.databind.ObjectMapper.enable([Lcom/fasterxml/jackson/core/JsonParser$Feature;)Lcom/fasterxml/jackson/databind/ObjectMapper;  com.amazonaws.internal.config.InternalConfig.<clinit> (InternalConfig.java:43)
```

**Comment by ptaoussanis** [comment]
Hi Daniel, sounds like a dependency conflict - please check your `lein deps :tree`

**Comment by dfcarpenter** [comment]
I updated to beta1 and there is no longer and issue. Thanks for the fast response.
